services:
  app:
    image: ${APP_IMAGE}
    container_name: career-case-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      NODE_ENV: production
